site_name: PrivateCloud
site_description: One-command Kubernetes private cloud installer
site_url: https://Kubenew.github.io/PrivateCloud
repo_name: Kubenew/PrivateCloud
repo_url: https://github.com/Kubenew/PrivateCloud

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Providers: providers.md

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences