import os
import subprocess
import json
import platform
from pathlib import Path
from typing import Optional


def run_cmd(cmd, timeout=30):
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False
        )
        return result
    except Exception as e:
        return type('obj', (object,), {'returncode': 1, 'stdout': '', 'stderr': str(e)})()


SYSTEMD_AVAILABLE = platform.system() == 'Linux' and os.path.exists('/etc/systemd')


def get_schedule_lines() -> list:
    result = run_cmd(['crontab', '-l'])
    if result.returncode == 0:
        return [line for line in result.stdout.strip().split('\n') if line and not line.startswith('#')]
    return []


def get_current_schedule() -> Optional[dict]:
    lines = get_schedule_lines()
    for line in lines:
        if 'privatecloud-backup-cron' in line:
            parts = line.split()
            if len(parts) >= 5:
                return {
                    'cron': ' '.join(parts[:5]),
                    'command': ' '.join(parts[5:]),
                }
    return None


def schedule_backup(interval: str, keep: int = 7, encrypt: bool = False) -> bool:
    cron_map = {
        'hourly': '0 * * * *',
        'daily': '0 2 * * *',
        'weekly': '0 2 * * 0',
        'monthly': '0 2 1 * *',
    }
    
    if interval not in cron_map:
        print(f"❌ Invalid interval: {interval}. Use: {', '.join(cron_map.keys())}")
        return False
    
    cron_expr = cron_map[interval]
    
    encrypt_flag = '--encrypt' if encrypt else ''
    cmd = f'privatecloud backup create {encrypt_flag} --keep-last {keep}'
    
    script_path = Path('/usr/local/bin/privatecloud-backup-cron')
    if script_path.exists() or os.access('/usr/local/bin', os.W_OK):
        script_content = f'''#!/bin/bash
# Auto-generated by PrivateCloud
# Keep {keep} backups, interval: {interval}
{cmd}
'''
        try:
            script_path.write_text(script_content)
            os.chmod(script_path, 0o755)
            full_cmd = f'/usr/local/bin/privatecloud-backup-cron'
        except Exception:
            full_cmd = cmd
    else:
        full_cmd = cmd
    
    full_cron_line = f'{cron_expr} {full_cmd}'
    
    if SYSTEMD_AVAILABLE:
        return schedule_systemd(interval, keep, encrypt)
    else:
        return schedule_cron(full_cron_line)


def schedule_cron(new_line: str) -> bool:
    lines = get_schedule_lines()
    
    filtered = [l for l in lines if 'privatecloud-backup-cron' not in l]
    
    current = '\n'.join(filtered)
    new_crontab = f'{current}\n# PrivateCloud backup schedule\n{new_line}\n'.strip()
    
    proc = subprocess.Popen(
        ['crontab', '-'],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )
    stdout, stderr = proc.communicate(input=new_crontab.encode())
    
    if proc.returncode == 0:
        print(f"✅ Cron job scheduled: {new_line}")
        return True
    else:
        print(f"❌ Failed to schedule cron: {stderr.decode()}")
        return False


def schedule_systemd(interval: str, keep: int, encrypt: bool) -> bool:
    unit_name = 'privatecloud-backup.timer'
    
    interval_map = {
        'hourly': 'OnBootSec=5min OnUnitActiveSec=1h',
        'daily': 'OnBootSec=10min OnUnitActiveSec=1d',
        'weekly': 'OnBootSec=10min OnUnitActiveSec=1w',
        'monthly': 'OnBootSec=10min OnUnitActiveSec=1mo',
    }
    
    timer_content = f'''[Unit]
Description=PrivateCloud Backup Timer ({interval})

[Timer]
{interval_map.get(interval, interval_map['daily'])}
Persistent=true

[Install]
WantedBy=timers.target
'''
    
    service_content = f'''[Unit]
Description=PrivateCloud Backup Service

[Service]
Type=oneshot
ExecStart=/usr/local/bin/privatecloud backup create --keep-last {keep}{' --encrypt' if encrypt else ''}
'''
    
    try:
        unit_path = Path('/etc/systemd/system')
        
        with open(unit_path / 'privatecloud-backup.timer', 'w') as f:
            f.write(timer_content)
        with open(unit_path / 'privatecloud-backup.service', 'w') as f:
            f.write(service_content)
        
        run_cmd(['systemctl', 'daemon-reload'])
        run_cmd(['systemctl', 'enable', 'privatecloud-backup.timer'])
        run_cmd(['systemctl', 'start', 'privatecloud-backup.timer'])
        
        print(f"✅ Systemd timer created: privatecloud-backup.timer ({interval})")
        return True
    except Exception as e:
        print(f"❌ Systemd scheduling failed: {e}")
        return False


def remove_schedule() -> bool:
    if SYSTEMD_AVAILABLE:
        try:
            run_cmd(['systemctl', 'stop', 'privatecloud-backup.timer'])
            run_cmd(['systemctl', 'disable', 'privatecloud-backup.timer'])
            run_cmd(['rm', '-f', '/etc/systemd/system/privatecloud-backup.timer', '/etc/systemd/system/privatecloud-backup.service'])
            run_cmd(['systemctl', 'daemon-reload'])
            print("✅ Systemd schedule removed")
            return True
        except Exception:
            pass
    
    lines = get_schedule_lines()
    filtered = [l for l in lines if 'privatecloud-backup-cron' not in l]
    
    proc = subprocess.Popen(
        ['crontab', '-'],
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )
    stdout, stderr = proc.communicate(input='\n'.join(filtered).encode())
    
    if proc.returncode == 0:
        print("✅ Cron schedule removed")
        return True
    
    print("❌ Failed to remove schedule")
    return False


def get_schedule_status() -> dict:
    if SYSTEMD_AVAILABLE:
        result = run_cmd(['systemctl', 'is-active', 'privatecloud-backup.timer'])
        if result.returncode == 0:
            return {
                'type': 'systemd',
                'active': True,
                'name': 'privatecloud-backup.timer',
            }
    
    cron_schedule = get_current_schedule()
    if cron_schedule:
        return {
            'type': 'cron',
            'active': True,
            'schedule': cron_schedule['cron'],
        }
    
    return {'type': None, 'active': False}